Push library on Clojars
=======================
:Author: Simone Mosciatti
:Email: simone@mweb.biz


==== Push library on Clojars

===== Problem

After having built a library in Clojure, you want to make it public so that anyybody can use it and simply add it.

===== Solution

In order to push code to Clojars, you need a Clojars account. Just go to clojars.org and register.

Complete the form for registration and note the field "SSH public key".

The SSH public key is used for encrypted transmission, and you may already have one.

In UNIX-like systems you just check if you have anything in your ~/.ssh directory. If you don't have anything, you can create a key using the command ssh-keygen -t rsa.

After you have the key, you open the .pub(lic) file (~/.ssh/id_rsa.pub in this case) and you copy it into the form field. It is okay to share your public key. It is public for a reason.

And now you have completed the registration on Clojars. Congrats :-)

The project.clj file is extremely important also for pushing the code. The first argument of defproject is the name of the library you are pushing, while the second argument is the version of such library.

For example, if you push a library with a project.clj like this:

[source, clojure]
----
(defproject cookbook "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.1"]])
----

It is important that after every change to your library, you remember to increment the version.

To actually push the code into Clojars you just need one single command:

[source, bash]
----
[simo@localhost cookbook]$ lein deploy clojars

WARNING: please set :description in project.clj.
WARNING: please set :url in project.clj.
No credentials found for clojars
See `lein help deploy` for how to configure credentials.
Username: cookbook
Password: 
Wrote /home/simo/cookbook/pom.xml
Created /home/simo/cookbook/target/cookbook-0.1.0-SNAPSHOT.jar
Could not find metadata cookbook:cookbook:0.1.0-SNAPSHOT/maven-metadata.xml in clojars (https://clojars.org/repo/)
Sending cookbook/cookbook/0.1.0-SNAPSHOT/cookbook-0.1.0-20130613.195025-1.pom (2k)
    to https://clojars.org/repo/
Sending cookbook/cookbook/0.1.0-SNAPSHOT/cookbook-0.1.0-20130613.195025-1.jar (2k)
    to https://clojars.org/repo/
Could not find metadata cookbook:cookbook/maven-metadata.xml in clojars (https://clojars.org/repo/)
Sending cookbook/cookbook/0.1.0-SNAPSHOT/maven-metadata.xml (1k)
    to https://clojars.org/repo/
Sending cookbook/cookbook/maven-metadata.xml (1k)
    to https://clojars.org/repo/

----

Whoever wants to use your code needs to add it to their project's dependencies:

[source, clojure]
----
[cookbook "0.1.0-SNAPSHOT"]
----
